#pragma once

#include <unistd.h>

#include <cstdint>
#include <cstring>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

using u8 = uint8_t;
using u32 = uint32_t;
using u64 = uint64_t;

// constexpr auto kMaxMsg = 4096;
constexpr auto kMaxMsg = 32 << 20; // likely larger than kernel buf

static void unix_error(const char *msg) {
  throw std::runtime_error(std::string(msg) + ": " + std::strerror(errno));
}

static int read_full(int fd, u8 *buf, size_t n) {
  while (n > 0) {
    const auto rv = read(fd, buf, n);
    if (rv == -1 && errno == EINTR)
      continue;
    if (rv <= 0)
      return -1;
    n -= rv;
    buf += rv;
  }
  return 0;
}

static int write_all(int fd, const u8 *buf, size_t n) {
  while (n > 0) {
    const auto rv = write(fd, buf, n);
    if (rv <= 0)
      return -1;
    n -= rv;
    buf += rv;
  }
  return 0;
}

struct Conn {
  int fd = -1;

  // app's intention, for the event loop

  bool want_read = false;
  bool want_write = false;
  bool want_close = false;

  // buffered in and out

  // data to be parsed by the app
  std::vector<u8> incoming;

  // responses generated by the app
  std::vector<u8> outgoing;
};

enum {
  RES_OK = 0,
  RES_ERR = 1,
  RES_NX = 2,
};

struct Response {
  u32 status = RES_OK;
  std::vector<u8> data;
};
